cargo-c.recipe: Ensure that we can change the id and rpath
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool:
changing install names or rpaths can't be redone for:
cargo-cinstall (for architecture arm64) because larger updated load commands do not fit
(the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1498>