librsvg.recipe: Fix build on MSYS2
The MSYS2 shell converts

--fprod " /* enumerations from \"@filename@\" */\n"

to

--fprod " /* enumerations from \"@filename@\" *C:/msys64/\n"

Due to: https://www.msys2.org/docs/filesystem-paths/

This converts the whole enum-types file into one big comment and
breaks the build:

ld: .libs/librsvg_2_la-rsvg-gobject.o: in function `rsvg_handle_class_init':
rsvg-gobject.c:231: undefined reference to `rsvg_handle_flags_get_type'

So, just remove those args. They're useless comments anyway.

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1216>