system_recipes: add expat recipe
Fix next error while compiling glib at Linux Arch:

```
[129/678] /home/rgonzalez/src/gitlab.freedesktop.org/gstreamer/cerbero/build/build-tools/bin/python gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../gio/org.freedesktop.portal.Documents.xml ../gio/org.freedesktop.portal.OpenURI.xml ../gio/org.freedesktop.portal.ProxyResolver.xml ../gio/org.freedesktop.portal.Trash.xml
FAILED: gio/xdp-dbus.h gio/xdp-dbus.c
/home/rgonzalez/src/gitlab.freedesktop.org/gstreamer/cerbero/build/build-tools/bin/python gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../gio/org.freedesktop.portal.Documents.xml ../gio/org.freedesktop.portal.OpenURI.xml ../gio/org.freedesktop.portal.ProxyResolver.xml ../gio/org.freedesktop.portal.Trash.xml
Traceback (most recent call last):
  File "/home/rgonzalez/src/gitlab.freedesktop.org/gstreamer/cerbero/build/sources/linux_x86_64/glib-2.82.4/b/gio/gdbus-2.0/codegen/gdbus-codegen", line 55, in <module>
    from codegen import codegen_main
  File "/home/rgonzalez/src/gitlab.freedesktop.org/gstreamer/cerbero/build/sources/linux_x86_64/glib-2.82.4/b/gio/gdbus-2.0/codegen/codegen_main.py", line 33, in <module>
    from . import parser
  File "/home/rgonzalez/src/gitlab.freedesktop.org/gstreamer/cerbero/build/sources/linux_x86_64/glib-2.82.4/b/gio/gdbus-2.0/codegen/parser.py", line 24, in <module>
    import xml.parsers.expat
  File "/usr/lib/python3.13/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib/python3.13/lib-dynload/pyexpat.cpython-313-x86_64-linux-gnu.so: undefined symbol: XML_SetAllocTrackerActivationThreshold
```

Arch Linux has expat version 2.7.3-1 and the recipe is 2.7.1. XML_SetAllocTrackerActivationThreshold was added at 2.7.2.

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1971>