nettle: add '-std=c99' to CFLAGS
This option is required when building on centos 7.

```
rsa-sign-tr.c: In function 'sec_equal':
rsa-sign-tr.c:243:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < limbs; i++)
   ^
rsa-sign-tr.c:243:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [rsa-sign-tr.o] Error 1
make[1]: Leaving directory `/home/joykim/git/cerbero/build/sources/linux_x86_64/nettle-3.4.1'
make: *** [all] Error 2
```