m4: Update to 1.4.21
Fixes compilation with gcc 15 (e.g. F44):

./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2232>