build-tools: Fix error copying removed site.py from setuptools
Ubuntu 22.04 Jammy Jellyfish produces next error on bootstrap:
```
Traceback (most recent call last):
  File "<string>", line 20, in <module>
...
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/src/cerbero/build/build-tools/local/lib/python3.10/dist-packages/site.py'
```

The error is produced because Ubuntu 22.04 Jammy Jellyfish uses
posix_local as sysconfig default scheme:
```
$ python -m sysconfig
Platform: "linux-x86_64"
Python version: "3.10"
Current installation scheme: "posix_local"

Paths:
        data = "/usr/local"
        include = "/usr/include/python3.10"
        platinclude = "/usr/include/python3.10"
        platlib = "/usr/local/lib/python3.10/dist-packages"
        platstdlib = "/usr/lib/python3.10"
        purelib = "/usr/local/lib/python3.10/dist-packages"
        scripts = "/usr/local/bin"
        stdlib = "/usr/lib/python3.10"

Variables:
...
```

To fix the issue the posix_prefix schema needs to be provided to get
the purelib path from the sysconfig.

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/947>