cerbero: \ in comments breaks execution as python script
```
File ./cerbero-uninstalled, line 76
   $PYTHON -c """
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 702-703: truncated \UXXXXXXXX escape
```

So escape the `\`. Hopefully people reading won't get confused.