openssl: fix linking on android/armv7
Linking an android application for armv7 would result in undefined references
with the 1.1.0h update because it seems configure can't seem to detect
the max available arm architecture anymore.  Fix by specifying on the
configure command

  crypto/evp/e_aes.c:1084: error: undefined reference to 'aes_v8_set_encrypt_key'
  crypto/evp/e_aes.c:1044: error: undefined reference to 'aes_v8_set_decrypt_key'
  crypto/evp/e_aes.c:1060: error: undefined reference to 'aes_v8_encrypt'
  crypto/evp/e_aes.c:1060: error: undefined reference to 'aes_v8_ctr32_encrypt_blocks'
  crypto/evp/e_aes.c:1060: error: undefined reference to 'aes_v8_cbc_encrypt'
  crypto/evp/e_aes.c:1060: error: undefined reference to 'bsaes_ctr32_encrypt_blocks'
  crypto/evp/e_aes.c:1060: error: undefined reference to 'aes_v8_decrypt'
  crypto/evp/e_aes.c:1060: error: undefined reference to 'bsaes_cbc_encrypt'
  crypto/evp/e_aes.c:1831: error: undefined reference to 'aes_v8_set_decrypt_key'
  crypto/evp/e_aes.c:1840: error: undefined reference to 'aes_v8_set_encrypt_key'
  crypto/evp/e_aes.c:1823: error: undefined reference to 'aes_v8_set_encrypt_key'
  crypto/evp/e_aes.c:1851: error: undefined reference to 'aes_v8_decrypt'
  crypto/evp/e_aes.c:1851: error: undefined reference to 'aes_v8_encrypt'
  crypto/evp/e_aes.c:1851: error: undefined reference to 'bsaes_xts_encrypt'
  crypto/evp/e_aes.c:1851: error: undefined reference to 'bsaes_xts_decrypt'
  crypto/evp/e_aes.c:1446: error: undefined reference to 'aes_v8_set_encrypt_key'
  crypto/evp/e_aes.c:1504: error: undefined reference to 'bsaes_ctr32_encrypt_blocks'
  crypto/evp/e_aes.c:1504: error: undefined reference to 'aes_v8_encrypt'
  crypto/evp/e_aes.c:1504: error: undefined reference to 'aes_v8_ctr32_encrypt_blocks'
  crypto/evp/e_aes.c:2068: error: undefined reference to 'aes_v8_encrypt'
  crypto/evp/e_aes.c:2480: error: undefined reference to 'aes_v8_set_decrypt_key'
  crypto/evp/e_aes.c:2525: error: undefined reference to 'aes_v8_decrypt'
  crypto/modes/gcm128.c:790: error: undefined reference to 'gcm_init_neon'
  crypto/modes/gcm128.c:785: error: undefined reference to 'gcm_gmult_neon'
  crypto/modes/gcm128.c:785: error: undefined reference to 'gcm_ghash_neon'
  crypto/armcap.c:53: error: undefined reference to '_armv7_tick'
  crypto/armcap.c:167: error: undefined reference to '_armv7_neon_probe'
  crypto/armcap.c:181: error: undefined reference to '_armv8_sha256_probe'
  crypto/armcap.c:186: error: undefined reference to '_armv7_tick'
  crypto/armcap.c:177: error: undefined reference to '_armv8_sha1_probe'
  crypto/armcap.c:170: error: undefined reference to '_armv8_pmull_probe'
  crypto/armcap.c:173: error: undefined reference to '_armv8_aes_probe'