bzip2.recipe: Fix build error in ffmpeg with MinGW
include/bzlib.h:114:17: error: two or more data types in declaration specifiers
include/bzlib.h:138:13: error: two or more data types in declaration specifiers
include/bzlib.h:214:21: error: two or more data types in declaration specifiers

Also touch bzip2.recipe so that it gets rebuilt.