recipes: downgrade openssl to 1.1.0g again
Version 1.1.0g seems to result in linking failures on Android:
  crypto/evp/e_aes.c:1084: error: undefined reference to 'aes_v8_set_encrypt_key'
  crypto/evp/e_aes.c:1060: error: undefined reference to 'bsaes_cbc_encrypt'
  crypto/modes/gcm128.c:790: error: undefined reference to 'gcm_init_neon'
  crypto/modes/gcm128.c:785: error: undefined reference to 'gcm_gmult_neon'
  crypto/modes/gcm128.c:785: error: undefined reference to 'gcm_ghash_neon'
  crypto/armcap.c:53: error: undefined reference to '_armv7_tick'
  crypto/armcap.c:167: error: undefined reference to '_armv7_neon_probe'
  crypto/armcap.c:181: error: undefined reference to '_armv8_sha256_probe'
  crypto/armcap.c:186: error: undefined reference to '_armv7_tick'
  crypto/armcap.c:177: error: undefined reference to '_armv8_sha1_probe'
  crypto/armcap.c:170: error: undefined reference to '_armv8_pmull_probe'
  crypto/armcap.c:173: error: undefined reference to '_armv8_aes_probe'
(and more in the same vein).

Revert until someone can investigate.

And remove comment about tarballs, redirects have been set up.