proxy-libintl.recipe: Fix detection with AM_GNU_GETTEXT
Without this, proxy-libintl is not detected correctly by projects that
are looking for gettext with the AM_GNU_GETTEXT autoconf macro. This
causes a build failure in gnutls while building libnice:

libgnutls.so: error: undefined reference to 'libintl_dgettext'
libgnutls.so: error: undefined reference to 'libintl_bindtextdomain'