cerbero: Fix gathering of invalid recipes
The `r` variable was used when it was not actually set.

```
UnboundLocalError: local variable 'r' referenced before assignment
```