-bad: temporal fix to pass the CI's with the new toolchain
'sys/d3dvideosink/75b8d49@@gstd3d@sha/d3dhelpers.c.obj' -c ../sys/d3dvideosink/d3dhelpers.c
../sys/d3dvideosink/d3dhelpers.c: In function 'd3d_format_to_string':
../sys/d3dvideosink/d3dhelpers.c:134:3: error: enumeration value 'D3DFMT_D32_LOCKABLE' not handled in switch [-Werror=switch]
   switch (format) {

Once the new toolchain is in use, d3dhelpers.c will be fixed to
handle the missing enumeration values.