recipes: gst-plugins-bad: explicitly disable more plugins
Sync up list of disabled plugins with the list from before the
move to meson. Some of the plugins that we are disabling now
hadn't been ported yet to meson at the time the recipe was
switched to meson.

Fixes build issue on ios due to missing/renamed openal header:
ext/openal/gstopenalsink.h:38:10: fatal error: 'OpenAL/alext.h' file not found