cerbero: Allow skipping steps in the recipe definition
Removing steps at runtime is racy, and causes this error
intermittently on the CI during bootstrap:

KeyError: 'relocate_osx_libraries'
Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/786>