cerbero: Use Path.glob() instead of `ls`
This is faster, especially on Windows, and also fixes these spammy
warnings:

Exception ignored when trying to write to the signal wakeup fd:
BlockingIOError: [Errno 11] Resource temporarily unavailable