Fix librsvg recipe FatalError for usupported RUST arch/platform
librsvg recipe is calling `self.config.rust_triple()` which raises
`FatalEror` for unsupported architecture/platform combinations. Then
when listing recipes with cbc configured for `cross linux x86` we get:

```
    $ /cerbero-uninstalled -c ./config/cross-lin-x86.cbc list
    Build tools install prefix will be /tmp/cerbero/build/build-tools
    Install prefix will be /tmp/cerbero/build/dist/linux_x86
    WARNING: Error loading recipe in file /tmp/cerbero/recipes/librsvg.recipe
    Traceback (most recent call last):
      File "/tmp/cerbero/cerbero/build/cookbook.py", line 492, in _load_recipes_from_file
        recipe = self._load_recipe_from_class(new_d[recipe_cls_key], self._config, filepath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/cerbero/cerbero/build/cookbook.py", line 515, in _load_recipe_from_class
        r.prepare()
      File "/tmp/cerbero/recipes/librsvg.recipe", line 73, in prepare
        self.target_triple = self.config.rust_triple(self.config.target_arch,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/cerbero/cerbero/config.py", line 1093, in rust_triple
        raise FatalError(f'Unsupported build platform/arch combination: {platform}/{arch}')
    cerbero.errors.FatalError: Fatal Error: Unsupported build
    platform/arch combination: linux/x86
```

This fix will make the recipe quit with `InvalidRecipeError`,
as expected, instead of `FatalError`.

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1814>