libkate.recipe: Fix subdirs editing when autoreconf is run
We were only modifying Makefile.in to change SUBDIRS to avoid
a forced-autoreconf. However, on non-Windows, we were running
autoreconf manually, so the Makefile.in changes were getting
overwritten.

Edit SUBDIRS in Makefile.am too when we run autoreconf, which
coincides with when we want to apply a configure.ac patch.

Fixes a build failure on latest Fedora:

```
make[4]: Entering directory '/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/armv7/libkate-0.4.1/tools/KateDJ'
/bin/sh /home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/armv7/libkate-0.4.1/misc/autotools/install-sh -d "/home/nirbheek/projects/repos/cerbero.git/1.22/build/dist/android_universal/armv7/lib/python3.12/site-packages/kdj"
for module in __init__ constants finder tools muxer demuxer tester options ui_main ui_editor ui_options; do \
  /usr/bin/install -c -m 644 "../../tools/KateDJ/kdj/$module.py" "/home/nirbheek/projects/repos/cerbero.git/1.22/build/dist/android_universal/armv7/lib/python3.12/site-packages/kdj"; \
  if test -z ""; then \
    ../../misc/autotools/py-compile --basedir "/home/nirbheek/projects/repos/cerbero.git/1.22/build/dist/android_universal/armv7/lib/python3.12/site-packages/kdj" "$module.py"; \
  else \
    ../../misc/autotools/py-compile --destdir "" --basedir "/home/nirbheek/projects/repos/cerbero.git/1.22/build/dist/android_universal/armv7/lib/python3.12/site-packages/kdj" "$module.py"; \
  fi \
done
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'imp'

[...]
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1414>