opencore-amr: pin cpp_std to c++11
this fixes the below compiler error caused with the newer NDKs
which support higher cpp_std versions

```
../opencore/codecs_v2/audio/gsm_amr/amr_nb/common/include/basic_op_c_equivalent.h:112:32:
      error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  112 |     static inline Word32 L_add(register Word32 L_var1, register Word32 L_var2, Flag *pOverflow)
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2111>