bootstrap: update pip to work around CentOS+Docker copy to tmp error
> ERROR: Could not install packages due to an EnvironmentError: [('/builds/gstreamer/cerbero/cb/sources/build-tools/meson-1.9.0/.git/objects/0a', '/tmp/pip-req-build-14a2blny/.git/objects/0a', "[Errno 2] No such file or directory: '/builds/gstreamer/cerbero/cb/sources/build-tools/meson-1.9.0/.git/objects/0a'"), ('/builds/gstreamer/cerbero/cb/sources/build-tools/meson-1.9.0/.git/objects/14', '/tmp/pip-req-build-14a2blny/.git/objects/14', "[Errno 2] No such file or directory: '/builds/gstreamer/cerbero/cb/sources/build-tools/meson-1.9.0/.git/objects/14'")]

See https://github.com/pypa/pip/issues/6265#issuecomment-524667548

(cherry picked from commit 3d54b5eb64a2044730bfd54088e6b9dfcf65d5c1)

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2256>