cerbero: Fix packaging on Windows
This broke in 8f0c0915f9332364409c75cbb8536025ed1dbebb, with the
changes in `packages/gstreamer-1.0/gstreamer-1.0.package`.

`self.platform_packages` gets added twice if we fetch `self.package`
twice in one assignment. We didn't notice this earlier because we only
use `platform_packages` on Windows.

> gstreamer-1.0-msvc-x86_64-1.17.2.wxs(150) : error LGHT0091 : Duplicate symbol 'Feature:_vsintegration_1.0' found. This typically means that an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
> gstreamer-1.0-msvc-x86_64-1.17.2.wxs(157) : error LGHT0092 : Location of symbol related to previous error.
> gstreamer-1.0-msvc-x86_64-1.17.2.wxs(153) : error LGHT0091 : Duplicate symbol 'Feature:_gstreamer_1.0_vs_templates' found. This typically means that an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
> gstreamer-1.0-msvc-x86_64-1.17.2.wxs(160) : error LGHT0092 : Location of symbol related to previous error.

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/536>