Raise error if recipes_remotes value for recipe is malformed
Expect a dict there. Better raise an explicit error than to fail
with "AttributeError: 'str' object has no attribute 'iteritems'"
if the value in ~/.cerbero/cerbero.cbc is malformed.

https://bugzilla.gnome.org/show_bug.cgi?id=792839