pygobject.recipe: Fix overflow when comparing GstMessageType on Windows
```
>>> from gi.repository import Gst
>>> Gst.init()
>>> c = Gst.StreamCollection.new('foobar')
>>> m = Gst.Message.new_stream_collection(None, c)
>>> m.type == Gst.MessageType.STATE_CHANGED or m.type == Gst.MessageType.EOS
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in method get_value of gi.FieldInfo object at 0x000001D2109FC750> returned a result with an exception set
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2098>