m4: Update to 1.4.18
It provides a newly generated configure script.

Fixes errors compiling in android bootstrap

In file included from freeze.c:23:0:
freeze.c: In function 'reload_frozen_state':
m4.h:146:27: error: this statement may fall through [-Werror=implicit-fallthrough=]
 #define M4ERROR(Arglist) (m4_error Arglist)
                         ~^~~~~~~~~~~~~~~~~
freeze.c:301:11: note: in expansion of macro 'M4ERROR'
           M4ERROR ((EXIT_FAILURE, 0, "ill-formed frozen file"));
           ^~~~~~~
freeze.c:303:9: note: here
         case 'C':
         ^~~~
cc1: all warnings being treated as errors

https://bugzilla.gnome.org/show_bug.cgi?id=784195