cerbero: Don't set old env to None for unset env vars
It's wrong (unset != None) and causes a traceback:

Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 279, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 358, in _do_step
    stepfunc()
  File "./cerbero/build/build.py", line 100, in call
    res = func(*args)
  File "./cerbero/build/build.py", line 582, in configure
    f = self.write_meson_cross_file()
  File "./cerbero/build/build.py", line 502, in write_meson_cross_file
    windres = self._old_env.get('WINDRES', '').split(' ')
AttributeError: 'NoneType' object has no attribute 'split'