ci: Mark a racy xcode toolchain bug for retrying
https://gitlab.freedesktop.org/gstreamer/cerbero/-/jobs/89862042

Log message pasted for posterity, slightly edited to fit in the commit
message line length restrictions.

```
cd /.../vvdec-3.0.0/b/source/Lib/vvdec
&& /usr/bin/clang++ -DTARGET_SIMD_X86 -DVVDEC_DYN_LINK -DVVDEC_SOURCE
-Dvvdec_EXPORTS
-I/.../vvdec-3.0.0/source/Lib/vvdec/../../../include
-I/.../vvdec-3.0.0/b
-I/.../vvdec-3.0.0/source/Lib/vvdec/.
-I/.../vvdec-3.0.0/source/Lib/vvdec/..
-I/.../vvdec-3.0.0/source/Lib/vvdec/../DecoderLib
-I/.../vvdec-3.0.0/source/Lib/vvdec/../CommonLib
-I/.../vvdec-3.0.0/source/Lib/vvdec/../CommonLib/x86
-I/.../vvdec-3.0.0/source/Lib/vvdec/../CommonLib/arm
-I/.../vvdec-3.0.0/source/Lib/vvdec/../libmd5
-isystem
/.../vvdec-3.0.0/source/Lib/vvdec/../../../thirdparty
-arch x86_64 -m64 -Wno-error=format-nonliteral
-Werror=unguarded-availability-new
-I/private/tmp/builds/gstreamer/cerbero/cb/dist/darwin_universal/x86_64/include
-mmacosx-version-min=10.13 -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk
-stdlib=libc++  -Wall -g -O2 -O3 -DNDEBUG -arch x86_64 -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk
-fPIC -fvisibility=hidden -fvisibility-inlines-hidden -msse4.1 -Wall
-Wno-unused-function -Wno-enum-compare-switch -Wno-unknown-attributes
-pedantic -Wno-error=pedantic -Wno-c++2a-extensions -Werror -std=c++14
-MD -MT
source/Lib/vvdec/CMakeFiles/vvdec.dir/__/CommonLib/Picture.cpp.o -MF
CMakeFiles/vvdec.dir/__/CommonLib/Picture.cpp.o.d -o
CMakeFiles/vvdec.dir/__/CommonLib/Picture.cpp.o -c
/.../vvdec-3.0.0/source/Lib/CommonLib/Picture.cpp
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool:
unknown char `A' in flag -DTARGET_SIMD_X86
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool
[-arch arch_type] [-fahlLDtdorSTMRIHGvVcXmqQjCP] [-mcpu=arg] [--version] <object file> ...
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2016>