macos, ios: update to Xcode 27 minimums
Fixes vvdec build:

FAILED: source/Lib/vvdec/CMakeFiles/vvdec_x86_simd.dir/__/CommonLib/x86/sse41/InterPred_sse41.cpp.o
(...snip...)
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX27.0.sdk/usr/include/c++/v1/algorithm:1840:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX27.0.sdk/usr/include/c++/v1/__config:15:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX27.0.sdk/usr/include/c++/v1/__configuration/availability.h:204:4: error: "The selected platform is no longer supported by libc++." [-Werror,-W#warnings]
  204 | #  warning "The selected platform is no longer supported by libc++."
      |    ^

See https://developer.apple.com/xcode/system-requirements/

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2357>