webrtc-audio-processing: Disable 64-bit file offsets on Android API < 24
This fails to build because C++ stdio is broken in Android API < 24
with -D_FILE_OFFSET_BITS=64:

```
In file included from ../subprojects/abseil-cpp-20230125.1/absl/flags/parse.cc:22:
/home/nirbheek/projects/repos/cerbero.git/build/android-ndk-21/sources/cxx-stl/llvm-libc++/include/fstream:950:9: error: use of undeclared identifier 'fseeko'
    if (fseeko(__file_, __width > 0 ? __width * __off : 0, __whence))
        ^
/home/nirbheek/projects/repos/cerbero.git/build/android-ndk-21/sources/cxx-stl/llvm-libc++/include/fstream:213:5: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::seekoff' requested here
    basic_filebuf();
    ^
/home/nirbheek/projects/repos/cerbero.git/build/android-ndk-21/sources/cxx-stl/llvm-libc++/include/fstream:1151:14: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::basic_filebuf' requested here
    explicit basic_ifstream(const string& __s, ios_base::openmode __mode = ios_base::in);
             ^
../subprojects/abseil-cpp-20230125.1/absl/flags/parse.cc:182:17: note: in instantiation of member function 'std::__ndk1::basic_ifstream<char, std::__ndk1::char_traits<char> >::basic_ifstream' requested here
  std::ifstream flag_file(flag_file_name);
                ^
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/686>