nettle/ios: pass -Wno-error=implicit-function-declaration for build compiler
Otherwise, nettle configure fails to find a build compiler and errors
out like so:

checking build system compiler gcc... no
checking build system compiler cc... no
checking build system compiler c89... no
checking build system compiler c99... no
configure: error: Cannot find a build system compiler

Due to the incompatible check:

conftest.c:4:3: error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
  exit(0);
  ^
conftest.c:4:3: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'

Part-of: <https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/648>